Repository Eoxia/reedcrm, pull requests merged in 2023-07, with the labels that each got.

#79 #72 [SQL] add: address data model
  core/modules/modEasyCRM.class.php
  sql/address/index.php
  sql/address/llx_easycrm_address.key.sql
  sql/address/llx_easycrm_address.sql
  sql/data.sql
  sql/llx_c_address_type.sql
Labels: 3, Data model, Enhancement

#80 #74 [Class] add: address class
  class/address.class.php
  core/modules/modEasyCRM.class.php
Labels: 3, Enhancement

#85 #73 [Address] add: views, template and tab in project
  core/modules/modEasyCRM.class.php
  core/tpl/easycrm_address_table_view.tpl.php
  view/address.php
Labels: 3, Enhancement

#78 #64 [Dashboard] add: two graphs on dashboard commstatus and refusal reason of pr
  class/easycrmdashboard.class.php
  core/modules/modEasyCRM.class.php
  easycrmindex.php
  langs/fr_FR/easycrm.lang
  sql/data.sql
  sql/index.php
  sql/llx_c_commercial_status.sql
  sql/llx_c_refusal_reason.sql
Labels: 3, Enhancement

#105 #87 [QuckCreation] fix: missing setOptionalsFromPost for extrafields
  core/tpl/easycrm_quickcreation_actions.tpl.php
  view/quickcreation.php
Labels: 2, Bug

#104 #100 [Address] fix: minor address issues
  .gitignore
  class/address.class.php
  core/modules/modEasyCRM.class.php
  core/tpl/easycrm_address_table_view.tpl.php
  sql/address/llx_easycrm_address.sql
  view/address_card.php
  view/map.php
Labels: 2, Bug, Enhancement

#111 #107 [Mod] add: dictionary in mod
  core/modules/modEasyCRM.class.php
  langs/fr_FR/easycrm.lang
  sql/data.sql
Labels: 1, Enhancement

#112 #110 [Hook] add: fetch_thirdparty in propal after edit extrafield
  class/actions_easycrm.class.php
  core/modules/modEasyCRM.class.php
Labels: 1, Bug

#113 #93 [Address] fix: reset action after action
  view/address_card.php
Labels: 0, Bug

#115 #101 [Map] fix: missing div in filter box
  view/map.php
Labels: 1, Bug

#116 #114 [Dashboard] fix: extrafields need check on empty value
  class/easycrmdashboard.class.php
Labels: 1, Bug

#117 #109 [Mod] add: new version number 1.1.0
  README.md
  core/modules/modEasyCRM.class.php
Labels: 0, Enhancement
