Repository Eoxia/reedcrm, pull requests merged in 2024-01, with the labels that each got.

#206 #205 [Mod] fix: menu entry foreach
  core/modules/modEasyCRM.class.php
Labels: 2, Bug

#190 #189 [Geolocation] add: geolocation object for manage projet location
  class/geolocation.php
  core/tpl/frontend/easycrm_project_quickcreation_frontend.tpl.php
  core/tpl/frontend/easycrm_quickcreation_actions_frontend.tpl.php
  js/easycrm.min.js
  js/modules/quickcreation.js
  langs/fr_FR/easycrm.lang
  sql/llx_element_geolocation.key.sql
  sql/llx_element_geolocation.sql
  view/frontend/quickcreation.php
  view/map.php
Labels: 5, Enhancement

#198 #197 [Lib] add: change pwa start url
  lib/easycrm.lib.php
Labels: 0, Enhancement

#210 #209 [QuickCreation] add: default mail for thirdparty
  core/tpl/easycrm_quickcreation_actions.tpl.php
Labels: 0, Enhancement

#211 #209 [QuickCreation] fix: need more infos like datetime
  core/tpl/easycrm_quickcreation_actions.tpl.php
Labels: 0, Enhancement

#213 #212 [SQL] add: c_actioncomm dico PHYSICAL_SALES_RELAUCH
  langs/fr_FR/easycrm.lang
  sql/data.sql
Labels: 0, Enhancement

#214 #212 [SQL] fix: change type for actioncomm PHYSICAL_SALES_RELAUCH
  sql/data.sql
Labels: 0, Enhancement

#199 #191 [Mod] add: new version number 1.3.0
  README.md
  core/modules/modEasyCRM.class.php
  core/triggers/interface_99_modEasycrm_EasycrmTriggers.class.php
Labels: 0, Enhancement
