Repository Eoxia/reedcrm, pull requests merged in 2024-06, with the labels that each got.

#249 #248 [Class] fix: remove type for $isextrafieldmanaged and $resprint
  class/actions_easycrm.class.php
  class/address.class.php
Labels: 0, Bug

#237 #236 [Hook] fix: do not type hook or fatal
  class/actions_easycrm.class.php
Labels: 0, Bug

#226 #222 [QuickCreation] fix: error opp_percent calcul
  core/tpl/frontend/easycrm_quickcreation_actions_frontend.tpl.php
  view/map.php
Labels: 2, Bug

#240 #220 [QuickCreation] add: percentage view
  core/tpl/frontend/easycrm_project_quickcreation_frontend.tpl.php
  js/easycrm.min.js
  js/modules/quickcreation.js
Labels: 1, Enhancement

#170 #116 [Mod] add: option to complete propal line desc
  admin/product.php
  core/triggers/interface_99_modEasycrm_EasycrmTriggers.class.php
  langs/fr_FR/easycrm.lang
  lib/easycrm.lib.php
Labels: 0, Enhancement
