Repository Eoxia/reedcrm, pull requests merged in 2024-08, with the labels that each got.

#275 #273 [Map] add: geolocation
  css/easycrm.min.css
  css/scss/element/_element.scss
  css/scss/element/_map-widget.scss
  langs/fr_FR/easycrm.lang
  view/map.php
Labels: 3, Enhancement

#278 #271 [Geolocation] fix: data model
  admin/address.php
  class/actions_easycrm.class.php
  class/address.class.php
  class/geolocation.class.php
  core/modules/modEasyCRM.class.php
  core/tpl/easycrm_address_table_view.tpl.php
  core/triggers/interface_99_modEasycrm_EasycrmTriggers.class.php
  js/easycrm.min.js
  js/modules/address.js
  langs/fr_FR/easycrm.lang
  lib/easycrm.lib.php
  sql/data.sql
  sql/llx_element_geolocation.key.sql
  sql/llx_element_geolocation.sql
  sql/update.sql
  view/address_card.php
  view/map.php
Labels: 8, Bug

#282 #173 [Address] fix: navigation from objecttype instead of fromtype
  core/tpl/easycrm_address_table_view.tpl.php
  langs/fr_FR/easycrm.lang
  view/address_card.php
Labels: 0, Bug

#284 #173 [Address] fix: fatal
  class/geolocation.class.php
  core/triggers/interface_99_modEasycrm_EasycrmTriggers.class.php
  view/address_card.php
Labels: 0, Bug

#285 #173 [Lang] fix: translation
  langs/fr_FR/easycrm.lang
Labels: 0, Translation

#286 #173 [Address] fix: update status
  view/address_card.php
Labels: 0, Bug

#293 #291 [Trigger] add: propal note should also be in trigger description
  core/triggers/interface_99_modEasycrm_EasycrmTriggers.class.php
Labels: 2, Enhancement

#295 #287 [Hook] fix: commercial relaunching handled on client tab
  class/actions_easycrm.class.php
Labels: 2, Bug

#294 #292 [QuickEvent] add : adding max length on label
  admin/setup.php
  core/modules/modEasyCRM.class.php
  js/easycrm.min.js
  js/modules/quickevent.js
  langs/fr_FR/easycrm.lang
  view/quickevent.php
Labels: 1

#297 #296 [Mod] add: new version number 1.5.0
  README.md
  core/modules/modEasyCRM.class.php
  core/triggers/interface_99_modEasycrm_EasycrmTriggers.class.php
Labels: 0, Enhancement

#300 #299 [Map] fix: fatal if empty object linked
  view/map.php
Labels: 0, Bug

#301 #299 [Map] fix: empty projects on pwa view
  view/map.php
Labels: 0, Bug
