Repository Eoxia/reedcrm, pull requests merged in 2024-07, with the labels that each got.

#253 #217 [QuickCreation] fix: use EASYCRM_THIRDPARTY_COMMERCIAL_VISIBLE
  core/tpl/easycrm_thirdparty_quickcreation.tpl.php
Labels: 0, Bug

#255 #246 [Hook] add: use popup dialog instead of redirection for comrelaunch
  class/actions_easycrm.class.php
  core/modules/modEasyCRM.class.php
  langs/fr_FR/easycrm.lang
  view/quickevent.php
Labels: 5, Enhancement

#232 #229 [Hook] add: mass action to assign opportunity status to projects
  class/actions_easycrm.class.php
  langs/fr_FR/easycrm.lang
Labels: 2, Enhancement

#256 #221 [QuickCreation] add: add const + check statut
  class/actions_easycrm.class.php
  core/modules/modEasyCRM.class.php
  core/tpl/frontend/easycrm_quickcreation_actions_frontend.tpl.php
  langs/en_US/easycrm.lang
  langs/fr_FR/easycrm.lang
Labels: 1, Enhancement

#257 #250 [Mod] fix: overwrite trad on actioncomm dico
  core/modules/modEasyCRM.class.php
  langs/fr_FR/easycrm.lang
  sql/data.sql
Labels: 1, Bug

#261 #260 [Hook] fix: display resprint
  class/actions_easycrm.class.php
Labels: 0, Bug

#259 #258 [Mod] add: new version number
  README.md
  core/modules/modEasyCRM.class.php
  core/triggers/interface_99_modEasycrm_EasycrmTriggers.class.php
Labels: 0, Enhancement

#268 #219 [Opportunity] add: link with map and improve code
  core/tpl/frontend/easycrm_project_quickcreation_frontend.tpl.php
  css/easycrm.min.css
  css/scss/layout/_header.scss
  view/map.php
Labels: 3, Enhancement

#269 #219 [QuickCreation] add: redirection to opportunity after creation
  core/tpl/frontend/easycrm_quickcreation_actions_frontend.tpl.php
  langs/fr_FR/easycrm.lang
Labels: 0, Enhancement

#270 #188 [Manifest] add: domain name to pwa name
  manifest.json.php
Labels: 0, Enhancement

#272 #268 [SQL] fix: forget comma in element_geolocation
  sql/llx_element_geolocation.sql
Labels: 0, Bug
