Repository Eoxia/reedcrm, pull requests merged in 2024-09, with the labels that each got.

#277 #276 [Public] add: audio button on frontend quickcreation project
  core/tpl/frontend/easycrm_project_quickcreation_frontend.tpl.php
  core/tpl/frontend/easycrm_quickcreation_actions_frontend.tpl.php
Labels: 1, Enhancement

#311 #310 [Hook] fix: saturneAdminPWAAdditionalConfig missing check
  class/actions_easycrm.class.php
Labels: 0, Bug

#313 #312 [QuickCreation] fix: usage of saturne_show_notice
  core/tpl/frontend/easycrm_project_quickcreation_frontend.tpl.php
Labels: 0, Bug

#318 #317 [Transifex] add: config transifex with github integration
  .tx/config
Labels: 2, Enhancement

#306 #305 [AdressCard] remove: random color in map
  view/map.php
Labels: 0, Enhancement

#307 #304 [Actions] add: address count badge on menu
  class/actions_easycrm.class.php
Labels: 2, Enhancement
